name: Code Review Workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ktlint:
    name: Check Code Style
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: file
